---
version: "3.7"

volumes:
  db:

services:
  neo4j:
    build: ./neo4j/
    volumes:
      - db:/data
    ports: # these are exposed only to allow access to neo4j browser
      - "7474:7474"
      - "7687:7687"
  genealdb:
    build: ./
    depends_on:
      - neo4j
    ports:
      - "8080:8080"
