---
version: "3.7"

volumes:
  neo4j:

services:
  neo4j:
    image: neo4j
    volumes:
      - neo4j:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
  genealdb:
    build: ./
    depends_on:
      - neo4j
    ports:
      - "8080:8080"
